# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_STORAGE_CONNECTION_STRING: 'BlobEndpoint=https://sast716.blob.core.windows.net/;QueueEndpoint=https://sast716.queue.core.windows.net/;FileEndpoint=https://sast716.file.core.windows.net/;TableEndpoint=https://sast716.table.core.windows.net/;SharedAccessSignature=sv=2020-02-10&ss=b&srt=sco&sp=rwdlacx&se=2022-03-11T02:50:47Z&st=2021-03-10T18:50:47Z&spr=https&sig=vhWteGA3pd52oo9CrjbMMcKZST1JwzXmOqDaC3saBd4%3D'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/enterprise/enterprise-web.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/enterprise'
    ArtifactName: 'enterprise-web.zip'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  enabled: false
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'enterprise-web.zip'
    downloadPath: '$(System.ArtifactsDirectory)/enterprise'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Subscription (2cc9b3c8-6bcc-4462-9f8f-83b16c02df57)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      az storage file upload-batch --source dist/* --destination '$web'