# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/enterprise/enterprise-web.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/enterprise'
    ArtifactName: 'enterprise-web.zip'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  enabled: false
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'enterprise-web.zip'
    downloadPath: '$(System.ArtifactsDirectory)/enterprise'

- task: AzureFileCopy@4
  inputs:
    SourcePath: 'dist/*'
    azureSubscription: 'Azure Subscription (2cc9b3c8-6bcc-4462-9f8f-83b16c02df57)'
    Destination: 'AzureBlob'
    storage: 'sast716'
    ContainerName: '$web'